### ISSUE TITLE
How to write a new table from a dplyr query without collecting in R

### ISSUE THREAD

**Issue by dsolito** [duckdb/duckdb-r#105]
Hi,

is it possible to (save a view? / register?) a result from a dplyr query with a duckdb table as source?
In this basic exemple, I collect or compute before saving to a new table.
Is it possible to bypass this ?
(My queries are often complex and this is not a real option for me to do it via SQL.)

`duck <- dbConnect(duckdb())`

```
duck |> 
  tbl(sql("select * from nested_table")) |>
  pivot_wider(names_from = key, values_from = c(str, int)) |>
  to_arrow() |>
  compute() |>
  to_duckdb(duck, "unested_table", auto_disconnect = FALSE) 
```

Thank you.

**Comment by nbc** [comment]
Hi,

If you want to create a table, you can directly use `dbplyr::compute` with name argument ([see compute doc](https://dbplyr.tidyverse.org/reference/collapse.tbl_sql.html) : 

```
library(duckdb)
library(dplyr)

duck <- dbConnect(duckdb())

duckdb_register(duck, "nested_table", iris)

# create an iris_table
duck |>
  tbl(sql("select * from nested_table")) |>
  compute(name = "iris_table", temporary = FALSE)

tbl(duck, "iris_table")
```

You can also create a view by using `dbplyr::sql_render` in `dbExecute` : 

```
sql <- duck |>
  tbl(sql("select * from nested_table")) |>
  dbplyr::sql_render(con = duck)

dbExecute(duck, glue::glue("CREATE OR REPLACE VIEW iris_view AS {sql}"))

tbl(duck, "iris_view")
```

**Comment by dsolito** [comment]
Hi @nbc 

I was not aware that compute() has arguments.
Your solutions work well.

Thank you. 
David

**Comment by krlmlr** [comment]
Thanks! Indeed, it's not super obvious from https://dplyr.tidyverse.org/reference/compute, but more detail is given at https://dbplyr.tidyverse.org/reference/collapse.tbl_sql.html that is linked from the former.

Closing.
