### ISSUE TITLE
`bigint = "integer64"` is not respected if `duckdb(dbdir = ...)` is used

### ISSUE THREAD

**Issue by lschneiderbauer** [duckdb/duckdb-r#107]
If the duckdb is created in-memory, int64 support is working as expected.
If the duckdb is created as a file, the bigint argument seems to unexpectedly be ignored.

Works:
``` r
library(DBI)

con <- dbConnect(duckdb::duckdb(bigint = "integer64"))

dbExecute(con, "CREATE TABLE t1 (id BIGINT)")
#> [1] 0
dbExecute(con, "INSERT INTO t1 VALUES (20)")
#> [1] 1

class(dbGetQuery(con, "SELECT id FROM t1")$id)
#> [1] "integer64"

dbDisconnect(con)
```

<sup>Created on 2024-03-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Does not work:

``` r
library(DBI)

con <- dbConnect(duckdb::duckdb(bigint = "integer64"), dbdir = tempfile())

dbExecute(con, "CREATE TABLE t1 (id BIGINT)")
#> [1] 0
dbExecute(con, "INSERT INTO t1 VALUES (20)")
#> [1] 1

class(dbGetQuery(con, "SELECT id FROM t1")$id)
#> [1] "numeric"

dbDisconnect(con)
```

<sup>Created on 2024-03-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

---

I am using duckdb-0.9.2-1

**Comment by lschneiderbauer** [comment]
I just realized that the title is slightly (but essentially) wrong.
This works as well:
``` r
library(DBI)

con <- dbConnect(duckdb::duckdb(bigint = "integer64", dbdir = tempfile()))

dbExecute(con, "CREATE TABLE t1 (id BIGINT)")
#> [1] 0
dbExecute(con, "INSERT INTO t1 VALUES (20)")
#> [1] 1

class(dbGetQuery(con, "SELECT id FROM t1")$id)
#> [1] "integer64"


dbDisconnect(con)
```

<sup>Created on 2024-03-14 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by nbc** [comment]
Hi,

I think this is similar to  https://github.com/duckdb/duckdb-r/issues/83#issuecomment-1962411622

**Comment by lschneiderbauer** [comment]
> Is this still an issue with v0.10.1, on CRAN now?

Sorry for the delayed response. It's not an issue anymore with v0.10.2. Thanks.

**Comment by lschneiderbauer** [comment]
therefore closing
