### ISSUE TITLE
Feature request: `n_distinct()` implementation w/ multiple arguments.

### ISSUE THREAD

**Issue by lschneiderbauer** [duckdb/duckdb-r#110]
Hi,

I understand that `n_distinct()` with multiple arguments is not supported for a generic dbplyr backend since SQL does not support that out of the box.

Is it possible to implement it in the case of duckdb using [structs](https://duckdb.org/docs/sql/data_types/struct)?

For example:
``` r
dbplyr::tbl_lazy(data.frame(x = 1, y = 1), duckdb::simulate_duckdb()) |>
summarize(l = n_distinct(x, y))
```
could be translated to
``` SQL
<SQL>
SELECT COUNT(DISTINCT {'x' : `x`, 'y' : `y`}) AS `l`
FROM `df`
```
which executes on duckdb.

**Comment by krlmlr** [comment]
Thanks, good idea! Would you like to contribute? I think the relevant code is in https://github.com/duckdb/duckdb-r/blob/main/R/backend-dbplyr__duckdb_connection.R .
