### ISSUE TITLE
add `temporary` parameter to `duckdb_read_csv()`

### ISSUE THREAD

**Issue by ThomasSoeiro** [duckdb/duckdb-r#142]
It is currently not possible to write a temporary table using `duckdb_read_csv()` directly.

To fix this, can we expose the `temporary` parameter in `duckdb_read_csv()`:

https://github.com/duckdb/duckdb-r/blob/b13d4050e3096c38a699719a2b5e89fc65106765/R/csv.R#L32-L33

and pass it to the call to `dbWriteTable()`?

https://github.com/duckdb/duckdb-r/blob/b13d4050e3096c38a699719a2b5e89fc65106765/R/csv.R#L70

---
For tables that fit in memory, we can use:

```r
mytable <- read.csv2("mytable.csv")
dbWriteTable(con, "mytable", mytable, temporary = TRUE)
```
But we are stuck for tables that don't fit in memory.

**Comment by krlmlr** [comment]
Thanks.

- The `dbWriteTable()` you mentioned really should be a `dbCreateTable()`, this had confused me a bit
- Can you confirm that running `dbExecute("COPY ... FROM ...")` does what you expect it to for temporary tables? What happens with name clashes (same table exists as permanent and as temporary table)?
- For now, you could work around:
    - Import the CSV data into a temporary database that you connect to your main database with `ATTACH`
    - Use something like `CREATE TEMPORARY TABLE ... AS read_csv_auto('...')` (not tested)

**Comment by krlmlr** [comment]
Temporary tables take precedence indeed if they exist:

``` r
library(duckdb)
#> Loading required package: DBI
con <- dbConnect(duckdb())

writeLines("a\n1", "x.csv")

dbExecute(con, "CREATE TEMPORARY TABLE x (a INTEGER)")
#> [1] 0

dbExecute(con, "CREATE TABLE x (y VARCHAR)")
#> [1] 0

dbExecute(con, "COPY x FROM 'x.csv' (HEADER)")
#> [1] 1

dbReadTable(con, "x")
#>   a
#> 1 1

dbRemoveTable(con, "x", temporary = TRUE)

dbReadTable(con, "x")
#> [1] y
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2024-08-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

We want to do the following here:

- In `duckdb_read_csv()`, change `dbWriteTable()` to `dbCreateTable()`
- Add an ellipsis after `files` to make sure arguments are named
- Add a `temporary = FALSE` argument and modify the SQL as needed

My preferred workflow is to use dbplyr with `tbl_function()`, but I'm open to reviewing a PR.
