### ISSUE TITLE
Error: String contains null byte

### ISSUE THREAD

**Issue by vincentarelbundock** [duckdb/duckdb-r#154]
Thanks for your great work on this package!

I get this error when trying to read a table into R and a string includes `\x0`, such as in row 201753 of the example database below:

`Error: String contains null byte`

To reproduce the issue, download my example database file (150MB):

```sh
wget https://arelbundock.com/example.duckdb
```

Reading the table into a Polars data frame works fine in Python:

```python
import polars
import duckdb
import pyarrow
con = duckdb.connect("example.duckdb")
df = con.sql("SELECT * FROM  sentences_narrative").pl()
print(df)
con.close()
```

But it generates an error in `R`:

```r
library(duckdb)
con = dbConnect(duckdb(), "example.duckdb")
df = dbGetQuery(con, "SELECT * FROM sentences_narrative")
dbDisconnect(con)
```

**Comment by krlmlr** [comment]
Thanks. This is a limitation of R, I've seen similar problems in a different scenario. You could use `encode()` to get the data as a BLOB for further wrangling in R, or perhaps convert the NUL bytes in duckdb.

``` r
con <- DBI::dbConnect(duckdb::duckdb())

DBI::dbWriteTable(con, "test", tibble::tibble(a = blob::blob(as.raw(c(33, 34, 0, 35)))))

DBI::dbReadTable(con, "test")
#>                a
#> 1 21, 22, 00, 23
```

``` r

DBI::dbExecute(con, "CREATE TABLE test2 AS SELECT decode(a) AS a FROM test")
#> [1] 1
```

``` r

DBI::dbReadTable(con, "test2")
#> Error: String contains null byte
```

``` r

DBI::dbGetQuery(con, "SELECT encode(a) FROM test2")
#>        encode(a)
#> 1 21, 22, 00, 23
```

<sup>Created on 2024-07-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for the info and workaround! Very interesting.

I'll let the repo owners close if appropriate.
