### ISSUE TITLE
Example does not use any of the functions in the man page

### ISSUE THREAD

**Issue by JosiahParry** [duckdb/duckdb-r#159]
The man page for `backend-duckdb` contains documentation for `simulate_duckdb`, `translate_duckdb`, `tbl_file` and `tbl_query`. The examples for this man page do not reference any of the functions that are documented in it.

https://github.com/duckdb/duckdb-r/blob/3e6b47da6c96128616e446833ff6991ed22aa810/R/backend-dbplyr__duckdb_connection.R#L8-L21

**Comment by krlmlr** [comment]
Thanks for raising this! Should be better now.
