### ISSUE TITLE
Appender used in `duckdb_read_csv()` and `dbAppendTable()`? 

### ISSUE THREAD

**Issue by JosiahParry** [duckdb/duckdb-r#170]
The docs for DuckDB state that the appender is implemented in a number of languages' APIs but R is not one of them. 
https://duckdb.org/docs/data/appender

However, perusing the source code _I think_ the appender is being used in this package and in a number of places. If so, is it documented how we can take advantage of it?

https://github.com/duckdb/duckdb-r/blob/2af70eb446e978e8abb5063d8b10c12d61bcb0d0/src/duckdb/src/include/duckdb/main/appender.hpp#L112

Thanks!

**Comment by krlmlr** [comment]
Thanks. We vendor the entire duckdb code base, but I can't see the appender being used in our bindings.

What problem would you like to solve with the appender?
