### ISSUE TITLE
Potential `rchk` issue

### ISSUE THREAD

**Issue by chainsawriot** [duckdb/duckdb-r#177]
Thank you very much for the package. I followed your method to deal with the "Non-API calls" issue for `cpp11` (duckdb/duckdb-r#145) and uploaded the package to CRAN. And CRAN now gave me [rchk issues](https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/readODS.out).

I somehow feel that it is a false positive and I have tried to make `duckdb` run through the same `rchk` via the container from `r-hub`. But the process was killed. Maybe my computer is too weak.

My experiment with protecting the `nms` does seem to cancel the `rchk` issue ropensci/readODS#190.

**Comment by krlmlr** [comment]
Thanks. Is this still an issue? I see new content in https://github.com/ropensci/readODS/issues/190.

**Comment by chainsawriot** [comment]
@krlmlr Yes, it is still an issue. The new content was to test and pinpoint the `rchk` issue to the untested path (which does not use `SETLENGTH`) in the truncate method of the original `cpp11`. And this cancels the `rchk` issue.

https://github.com/r-hub2/educated-yogic-starfish-rrrrrr/compare/04a1cab..2137a61

**Comment by krlmlr** [comment]
I don't follow. How can I help, is there anything we need to fix here? As far as I can tell, duckdb is fine.

**Comment by chainsawriot** [comment]
According to the discussion [here](https://github.com/r-lib/cpp11/pull/358#issuecomment-2201079178), this can be a false positive of rhck. If duckdb is fine, then I think I can close this.
