### ISSUE TITLE
connect to existing sqlite and postgres database

### ISSUE THREAD

**Issue by Yousuf28** [duckdb/duckdb-r#183]
Hi, 
Thanks for the duckdb R package. 
I have sqlite and postgres database. 
I was able to install and load the extension like this
```
library(duckdb)
library(DBI)
con <- dbConnect(duckdb::duckdb())
dbExecute(con, "INSTALL 'sqlite_scanner.duckdb_extension.gz'")
dbExecute(con, "INSTALL 'postgres_scanner.duckdb_extension.gz'")
dbExecute(con, "LOAD postgres")
dbExecute(con, "LOAD sqlite")
```
untils this works fine.
Now, How can I connect to my existing sqlite database.
For example If I connect like this, I get error that database does not have ID table.
But this database have ID table. 
What I am missing?
```
path <- 'file_path/sqlite/database.db'
con_sql <- DBI::dbConnect(duckdb(), path = path)
dbGetQuery(con_sql, 'select * from ID limit 5')



```

Also I would appreciate If anyone give an example how to connect to postgres database and query with an example.

**Comment by eitsupi** [comment]
If this is not an R-specific problem (i.e., if you reproduce the same problem using the duckdb CLI), I suggest you ask the question in the main DuckDB repository rather than here.
https://github.com/duckdb/duckdb/discussions

**Comment by krlmlr** [comment]
Do you need `dbExecute(conn, "ATTACH ...")` following https://github.com/duckdb/sqlite_scanner?tab=readme-ov-file#reading-data-from-sqlite ?
