### ISSUE TITLE
Vendoring broken

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb-r#190]
With https://github.com/duckdb/duckdb/pull/12636.

https://github.com/duckdb/duckdb-r/actions/runs/9722578776/job/26836690380#step:8:683

```
statement.cpp: In function ‘SEXPREC* rapi_execute(duckdb::stmt_eptr_t, bool, bool)’:
statement.cpp:345:39: error: ‘IsFinishedOrBlocked’ is not a member of ‘duckdb::PendingQueryResult’
  345 |         } while (!PendingQueryResult::IsFinishedOrBlocked(execution_result));
      |                                       ^~~~~~~~~~~~~~~~~~~
```

**Comment by krlmlr** [comment]
@Tishj: `PendingQueryResult::IsFinishedOrBlocked()` is gone after https://github.com/duckdb/duckdb/pull/12636, is it safe to replace with `PendingQueryResult::IsFinished()` ?

In #90, I introduced `PendingQueryResult::IsFinishedOrBlocked()` that seemed necessary back then, cherry-picking a commit by @Tmonster: https://github.com/duckdb/duckdb-r/pull/90#discussion_r1659657799 .

Thanks!

**Comment by Tishj** [comment]
@krlmlr Yes, that change was introduced by <https://github.com/duckdb/duckdb/pull/12636>
You should now use `PendingQueryResult::IsResultReady` no matter if the result collector is materialized or streaming

**Comment by krlmlr** [comment]
Fixed now, thanks!
