### ISSUE TITLE
Need cpp11 update

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb-r#191]
requested by CRAN due to `SYMVALUE` .

**Comment by yutannihilation** [comment]
I filed the same issue (https://github.com/duckdb/duckdb-r/issues/187) a few days ago. I'm closing mine in favor of this.

**Comment by krlmlr** [comment]
Thanks, good catch. I should have checked before.

**Comment by yutannihilation** [comment]
@krlmlr 
Are you working on releasing the fix, or did you already communicate with the CRAN maintainers about this? I'm a bit anxious because the deadline is approaching.

https://cran.r-project.org/package=duckdb

**Comment by krlmlr** [comment]
Thanks, Hiroaki. I have a local branch that updates cpp11, it's going to be fine. Due to the failing "additional checks", the release will need manual approval, but the package will most likely stay on CRAN.

**Comment by yutannihilation** [comment]
Thanks for sharing the details! Good to know.

**Comment by krlmlr** [comment]
On CRAN now.

**Comment by yutannihilation** [comment]
Thanks for your great work!
