### ISSUE TITLE
Listing all past contributors

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb-r#2]
Will simplify future investigations.

**Comment by rsund** [comment]
You have removed the contributors history, i.e. it is no longer possible to see here who contributed and what in a way it was seen in the original DuckDB repo.

**Comment by krlmlr** [comment]
Thanks, good catch. I had not considered this. I see how credit is important, let me think about a solution here.

**Comment by hannes** [comment]
How about putting an explicit acknowledgement into the README and the DESCRIPTION for significant contributions?
