### ISSUE TITLE
Are binaries available on CRAN?

### ISSUE THREAD

**Issue by bdforbes** [duckdb/duckdb-r#201]
When I try to install DuckDB using the recommended `install.packages("duckdb")`, it spends forever compiling from source. Should binaries be available on CRAN? I'm using Windows 11, with R 4.4.1 and trying to install `duckdb` 1.0.0-2.

**Comment by krlmlr** [comment]
Binaries are available on CRAN for Windows and macOS: 

https://cran.r-project.org/web/packages/duckdb/index.html

![image](https://github.com/user-attachments/assets/15e6ec10-77ab-4b3d-80f2-6d4c0156c1bc)

It might take a few days after each release for them to be built on both platforms. Use https://p3m.dev/client/ for binary packages for Linux.

**Comment by bdforbes** [comment]
Thanks, that makes sense. I ended up just using a specific version where the binary was already available.
