### ISSUE TITLE
"Bleeding edge" install instructions don't pull latest duckdb

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb-r#25]
The readme suggests running `R CMD INSTALL .` on this repository to get "the bleeding edge", but this doesn't get the latest version of the underlying duckdb C++ library.

Would be nice to have shorthand instructions for installing the package with the latest version of both duckdb-r and duckdb, and to have those instructions added to the installation instructions in duckdb-web, the moreso since there seems to be a large delay between releases of libduckdb and the R package.

**Comment by Tmonster** [comment]
Hi David,

You are correct that just `R CMD INSTALL .` won't install the latest version of duckdb. In the [Building](https://github.com/duckdb/duckdb-r#building) section you can find instructions on how to use duckdb-r with the latest duckdb features. 

Would you rather see these instructions under a "Install Bleeding Edge" header?

**Comment by david-cortes** [comment]
> Hi David,
> 
> You are correct that just `R CMD INSTALL .` won't install the latest version of duckdb. In the [Building](https://github.com/duckdb/duckdb-r#building) section you can find instructions on how to use duckdb-r with the latest duckdb features.
> 
> Would you rather see these instructions under a "Install Bleeding Edge" header?

Yes, would be ideal if they would be put there alongside with the necessary git commands, and would be ideal to have them as instructions under duckdb.org too.
