### ISSUE TITLE
Expose the internal default connection and `sql` function?

### ISSUE THREAD

**Issue by eitsupi** [duckdb/duckdb-r#32]
The `sql` function used internally would be useful to perform processing via DuckDB. (e.g., reading Parquet files).

https://github.com/duckdb/duckdb-r/blob/d243b5301bdca5e642a4579ced6fd7f7b9ded04e/R/sql.R#L1-L15

Would you consider exporting this with a name like `duckdb_query`?

**Comment by krlmlr** [comment]
This function and the associated `default_connection()` is not really used even internally. We're free to design it to our desires, but I'd like to understand the motivation and use case. Most of that can be achieved today with DBI too?

**Comment by krlmlr** [comment]
Can we do a draft/pilot in a separate package, on top of DBI, before committing here?

**Comment by eitsupi** [comment]
I don't have time to work on this right away, but I'm assuming the same thing below that you can use with polarssql.

https://rpolars.github.io/r-polarssql/reference/polarssql_query.html

```sql
polarssql_register(mtcars = mtcars)

query <- "SELECT * FROM mtcars LIMIT 5"

# Returns a polars LazyFrame
polarssql_query(query)

# Clean up
polarssql_unregister("mtcars")
```

**Comment by stephhazlitt** [comment]
I noticed this `duckdb:::sql()` internal function used in today's [duckdb blog post](https://duckdb.org/2024/10/09/analyzing-open-government-data-with-duckplyr.html) which also made me wonder if it might be worth exporting the function?

**Comment by krlmlr** [comment]
FWIW, duckplyr now has `ducksql()` . Still hesitant to expose it here.
