### ISSUE TITLE
Returning a duckdb table to R via tbl() prints an error if a schema name is used

### ISSUE THREAD

**Issue by BorgeJorge** [duckdb/duckdb-r#39]
con <- dbConnect(duckdb())
dbWriteTable(con, "mtcars", mtcars)

\# the following works:
tbl(con,"mtcars")

\# the following also seems to work, but it prints an error: "It looks like you tried to incorrectly use a table in a schema as source."
tbl(con,"main.mtcars")

\# The error is printed whenever you use tbl() with a schema name

**Comment by m-muecke** [comment]
That is not a duckdb issue. You have to use the `dbplyr::in_schema` function, i.e. `tbl(con, in_schema("schema", "table")`. If you don't specify the table schema in the write table it will write to the default schema anyway. If you want to specify the schema for the table location when writing the table you need to specify it with `DBI::Id(schema = "schema", table = "table")`
