### ISSUE TITLE
Switch from read.csv to vroom for CSV Imports in `duckdb_read_csv`

### ISSUE THREAD

**Issue by denis-or** [duckdb/duckdb-r#459]
Hello, first of all, thank you for the great work on this package!

While evaluating the duckdb_read_csv function, I noticed that it currently uses read.csv for CSV file importation. However, as we know, read.csv can be quite slow for large files compared to more efficient alternatives, such as the vroom package ([benchmark vroom](https://vroom.r-lib.org/articles/benchmarks.html), [benchmark arrow](https://ursalabs.org/blog/2021-r-benchmarks-part-1/)) which provides significantly faster file reading.

I would like to suggest replacing read.csv with vroom::vroom to optimize the CSV import performance. Moreover, vroom offers a col_types argument, allowing users to specify the column types during the file read, which can be useful for ensuring data consistency.

In the code:

```r
duckdb_read_csv <- function(conn, name, files, header = TRUE, na.strings = "", nrow.check = 500,
                            delim = ",", quote = "\"", col.names = NULL, lower.case.names = FALSE,
                            sep = delim, transaction = TRUE, ...) {
  #
  if (length(na.strings) > 1) stop("na.strings must be of length 1")
  if (!missing(sep)) delim <- sep

  headers <- lapply(files, utils::read.csv, sep = delim, na.strings = na.strings, quote = quote, 
                                        nrows = nrow.check, header = header, ...)
```

by this:

```r
duckdb_read_csv <- function(conn, name, files, header = TRUE, na.strings = "", nrow.check = 500,
                            delim = ",", quote = "\"", col.names = NULL, col.types = NULL, 
                            lower.case.names = FALSE, sep = delim, transaction = TRUE, ...) {


  if (length(na.strings) > 1) stop("na.strings must be of length 1")
  if (!missing(sep)) delim <- sep

  # Using vroom for optimization
  headers <- lapply(files, vroom::vroom, delim = delim, na = na.strings, quote = quote, 
                    n_max = nrow.check, col_names = header, col_types = col.types, ...)

```

I think this suggestion could also address concerns raised in issues #118, and #383. The column type would be:
```r
col.types <- vroom::cols(
  column1 = vroom::col_character(),
  column2 = vroom::col_double(),
  column3 = vroom::col_date(format = "%Y-%m-%d")
)
```

I understand that introducing a new dependency like vroom to the package might be a consideration, as it could increase the package's complexity or size. However, there are significant performance gains to be had when using faster CSV importing packages like vroom, data.table::fread, or readr::read_csv, all of which offer substantial improvements in file loading speed for large datasets compared to read.csv. These alternatives could potentially enhance the performance of the package without drastically affecting the core structure, depending on your development priorities.

**Comment by toppyy** [comment]
If I'm not mistaken, `utils::read.csv`is only used to read a small subset of rows (500 by default) from the CSV-file to get the headers, so performance should not be an issue?

The actual work of reading the entire CSV  is done by duckdb's [COPY](https://duckdb.org/docs/sql/statements/copy.html):
```R
for (i in seq_along(files)) {
    thefile <- dbQuoteString(conn, enc2native(normalizePath(files[i])))
    dbExecute(conn, sprintf("COPY %s FROM %s (DELIMITER %s, QUOTE %s, HEADER %s, NULL %s)", tablename, thefile, dbQuoteString(conn, delim), dbQuoteString(conn, quote), tolower(header), dbQuoteString(conn, na.strings[1])))
}
  ```

**Comment by krlmlr** [comment]
Thanks, both. Today, we'd probably also use duckdb's own `sniff_csv()` function: https://duckdb.org/docs/data/csv/auto_detection .
