### ISSUE TITLE
Backslash doesn't escape metacharacters in duckdb for R

### ISSUE THREAD

**Issue by BorgeJorge** [duckdb/duckdb-r#47]
I haven't tried all the metacharacters, but the following commands in the R version of duckdb:

```r
dbGetQuery(con,"select regexp_matches('blah','\?')")
dbGetQuery(con,"select regexp_matches('blah','\.')")
dbGetQuery(con,"select regexp_matches('blah','\*')")
dbGetQuery(con,"select regexp_matches('blah','\+')")
```

all return an error of the form: 
```
Error: '\?' is an unrecognized escape in character string (<input>:1:48)
```

Even though all these commands work in the CLI version. Am I doing something wrong?

Thanks.

**Comment by mattsams89** [comment]
You need to use double backslash. E.g.

```
dbGetQuery(con, "SELECT REGEXP_MATCHES('hello?', '\\?')")

regexp_matches('hello?', '\\?')
1                            TRUE

dbGetQuery(con, "SELECT REGEXP_REPLACE('hello?', '\\?', '.')")

regexp_replace('hello?', '\\?', '.')
1                               hello.
```

**Comment by BorgeJorge** [comment]
Ah, thank you so much! I don't know regex that well, but if this isn't standard RE2 syntax, it might make sense to add this to either the R page or the Pattern Matching page in the documentation.

**Comment by krlmlr** [comment]
The code is rejected by R's interpreter. For recent versions of R, you could use raw strings. Or you can escape the backslash so that it is then passed to the regex engine. In any case, the engine sees `\?` .

See also https://r4ds.hadley.nz/strings.html .


``` r
r"(select regexp_matches('blah', '\?'))"
#> [1] "select regexp_matches('blah', '\\?')"
"select regexp_matches('blah', '\\?')"
#> [1] "select regexp_matches('blah', '\\?')"
```

<sup>Created on 2023-12-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
