### ISSUE TITLE
GitHub release?

### ISSUE THREAD

**Issue by eitsupi** [duckdb/duckdb-r#615]
It seems that 1.1.3 does not have a GitHub release.

**Comment by kent37** [comment]
Possibly the cause of #623 and #624?

**Comment by krlmlr** [comment]
Thanks for reporting. Fixed by https://github.com/cynkra/fledge/pull/848 . I will trigger later today, or it will auto-run tomorrow.

**Comment by eitsupi** [comment]
Hm, was that really fixed?

**Comment by krlmlr** [comment]
Next try.

**Comment by krlmlr** [comment]
Good now.
