### ISSUE TITLE
Support for hive partitioning

### ISSUE THREAD

**Issue by ArthurAndrews** [duckdb/duckdb-r#64]
Hive partitioning is a new feature of the duckdb CLI.  [hive_partitioning](https://duckdb.org/docs/archive/0.9.2/data/partitioning/hive_partitioning)

Is this currently supported in the R package?  If not, are there any plans to do so?

Thanks to all the developers.

**Comment by eitsupi** [comment]
Supported.

Here is an example on the website:
https://github.com/duckdb/duckdb-web/blob/5fb7a6bf85efae9fdd4094518e4027c9f8946909/docs/api/r.md?plain=1#L128-L137

**Comment by ArthurAndrews** [comment]
Thank you!
