### ISSUE TITLE
The CLI cannot open a duckdb database created in R using version 1.1.3 or 1.1.3-1

### ISSUE THREAD

**Issue by BorgeJorge** [duckdb/duckdb-r#640]
This is under windows 10, and the bug seems to have crept in after version 1.0.0 for R, since this isn't a problem using that version. So for example, after running:

```r
library(duckdb) # 1.1.3 or 1.1.3-1
con <- dbConnect(duckdb(), dbdir = 'mydb.duckdb')
dbExecute(con, "create table test as select 1")
dbDisconnect(con, shutdown = TRUE)
```
This is what happens in the CLI when you try to open the database:
```cli
D .open mydb.duckdb
Error: unable to open database "mydb.duckdb": IO Error: Cannot open file "mydb.duckdb": Access is denied.
```
The database also can't be opened in DBeaver, but it remains openable in R, and is also openable in Python.

**Comment by krlmlr** [comment]
Thanks. What happens if you call `gc()` or restart the R session?

**Comment by BorgeJorge** [comment]
Interesting. I have the same problem whether or not I use gc() or restart R, but I realized that I've been having this problem on my "production" machine that runs an ancient installation of Windows Server 2016, NOT Windows 10. When I switch to a Windows 10 machine I can't replicate the problem! This is not the first time I've gotten flaky results from my Windows Server computer, so please ignore this problem, sorry to have troubled you!
