### ISSUE TITLE
dbExecute(con, "load 'httpfs';") Failed

### ISSUE THREAD

**Issue by bergest** [duckdb/duckdb-r#65]
hi 
I have a problem with duckdb in R 

library(duckdb)
con <- dbConnect(duckdb::duckdb())
# dbExecute(con, "INSTALL 'fts';")
# dbExecute(con, "LOAD 'fts';")
dbExecute(con, "install 'httpfs';")
dbExecute(con, "load 'httpfs';")

dbExecute(con, "install 'httpfs';")  is OK 
but dbExecute(con, "load 'httpfs';") Failed  

Error: rapi_execute: Failed to run query
Error: IO Error: Extension "C:\Users\.....\AppData\Roaming\R\data\R\duckdb\.duckdb\extensions\2414840843\windows_amd64_rtools\httpfs.duckdb_extension" could not be loaded: Le module spécifié est introuvable.

regards

**Comment by lepennec** [comment]
The same issue is also opened in duckb/duckd:
https://github.com/duckdb/duckdb/issues/8243

**Comment by krlmlr** [comment]
There's nothing we can do here, let's continue the discussion in https://github.com/duckdb/duckdb/issues/8243.
