### ISSUE TITLE
Implement a way to access the new ALTREP lists

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb-r#95]
~~Starting with the relational API.~~

Opt-in for `dbGetQuery()` . The relational API and duckplyr are currently missing too many pieces.

**Comment by krlmlr** [comment]
@Antonov548: Start with these places:

- `rapi_rel_to_altrep()`
- `RelToAltrep::Initialize()`

**Comment by krlmlr** [comment]
I'll post a test case here.

**Comment by Antonov548** [comment]
I have checked current implementatons of altrep. 

Would be nice to have an example for it. Is idea to have altrep return type for `dbGetQuery`? Shouldn't it be then implemented in DBI?

**Comment by krlmlr** [comment]
Done in #77.

🤦 

I'll open new issues with specific examples.
