### ISSUE TITLE
Array returns "unknown column type" in 0.9.99.9000 when getting the results of a query

### ISSUE THREAD

**Issue by BorgeJorge** [duckdb/duckdb-r#99]
After installing 0.9.99.9000, array references (such as array_value(1,2,3)) return "unknown column type" to dbGetQuery(). For example:
```
con <- dbConnect(duckdb())
dbGetQuery(con,"select array_value(1,2,3)")
```
returns:
```
Error: rapi_prepare: Unknown column type for prepare: INTEGER[3]
```
Whereas a list reference:
```
dbGetQuery(con,"select list_value(1,2,3)")
```
displays the list:
```
  list_value(1, 2, 3)
1             1, 2, 3
```
Array creation in general appears to work within ddb 0.9.99.9000, however.

**Comment by krlmlr** [comment]
Is this a duplicate of #102?

**Comment by BorgeJorge** [comment]
It's a duplicate in that it's the same problem as #102, but I wanted to make sure people knew the problem persisted across version numbers. But I'll close it.
